# curl -u premysl.vyhnal@gmail.com -H 'X-GitHub-OTP: XXX'  -d '{"scopes":["public_repo"],"note":"XXX token name XXX"}'   https://api.github.com/authorizations


language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
sudo: true # for libzip (which is needed for love-release) - until travis updates to newer image
install: true
addons:
  apt:
    packages:
      - lua5.1
      - luarocks
      - imagemagick # android icons
git:
    submodules: false # Handle git submodules yourself

before_install:
        - test -f .gitmodules && sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules && git submodule update --init --recursive || echo "no gitmodules"
        - export PATH="~/.luarocks/bin:$PATH" # - "`luarocks path --bin`" # execute the luarocks output - sets the paths for 'local' tree
        
        - luarocks install --local luacheck

        - if [[ -n "$TRAVIS_TAG" ]] ; then luarocks install --local luarocks; fi # update
        - if [[ -n "$TRAVIS_TAG" ]] ; then sudo sed -i 's/trusty/xenial/g' /etc/apt/sources.list && sudo apt-get update -q && sudo apt-get upgrade -y; fi
        - if [[ -n "$TRAVIS_TAG" ]] ; then sudo apt-get install -y  libzip-dev fakeroot ; fi
        - if [[ -n "$TRAVIS_TAG" ]] ; then luarocks install --local luarocks; fi # update
        - if [[ -n "$TRAVIS_TAG" ]] ; then luarocks install --local love-release; fi


#script: "if [[ -n $TRAVIS_TAG ]] ; then ./build.sh dist; ./build.sh web; else ./build.sh; fi" # web only for tags
script: "if [[ -n $TRAVIS_TAG ]] ; then ./build.sh dist; else ./build.sh; fi" # dist only for tags
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # travis encrypt <token>
    secure: "50czcJQJ+wd6vluTUiIW2uAy8kZJONEc1o2Bd1+VxWZ/oaJJwxmRRUYSOZRjYLhYycaAYoAYP3mIvvCS9Rs/6sfVN+AI/FfyHjHZnNn0cfVM6EO5tCdkihfpZ8fDpOv+3q3gZCRVVUuwKTgR7UH6xr4xzB+M7Cj1QuRkpXLqyLKVKFI52X4AIfoxwsDhSudJmstZagdcdJv6cpq7UiI6T6I/gafX/gcOR6IhaGkOhPjCfwjGxAr1kNjQtvjBzLpwCKO3yHYgIXV/9xG38PcKOCGLwSdyZC492yW1ZzsoNwhxHDQJZAigeTFwVwLx5dQuygd7FVKJH4y3YBMYpyinReVJ02Et1MeTiEWI2QIzmTqeapIIixIYv996zCDskNgFstrztILOo5E8od1+wDjUuyEGq7+pDNg3hJjsx7XZgvyl2R9uRRKfkdLNk2IoE5AQmfdl2o5lRMULDGgVdzHkdcf6b+TPT1xHc+z7p8oSqhdVBQjEdZ5UMkBAeVFuSoL6SqG7TbahjQHOXrdpYCBOcsH+q1TTDMwxtUnS/FrbX3VGf4jjiS06LtER/7DMvepx/Dw9w06VusBKObYmGrXHd2THnQG3XmZKsWB/WmF/Qzp/mqyhocU0sbdmCH+kJ9L+IpjT9gFbKRCVRtHRAXi2vJmQhiilOTOpE3kANTO3EAs="
  file_glob: true
  file:
    - target/cuet*
  on:
    tags: true
    all_branches: true
after_success:
- "[[ -n $TRAVIS_TAG ]] && ./build.sh deploy $TRAVIS_REPO_SLUG"
env:
  global:
   # travis encrypt GH_TOKEN=<token>
  - secure: "symU9a8jIHAOZlHrviVKkqNR92kYmqFbIMtGeD2yrJzqD3QI6eMwJnxVx7+yReTNf6Px5WyktlcdOajH0t/mdkibUxjw6UUdPUyEuPnFsB0IFGA3bf8m2THqObRhiPgGPei/mTBNIv58PfU1Wr5rGRY/eEZ3zi67vLxKWZFOIzpIG3canKLFzs5JtIryZxbimIUmgU8Y0619t5VqZ+tl20h7s3bfQGWA2DousbwCAWchV0d5ppiAKqGq0CjV+dGJqSV7HR9MurmskC2TfltbX47/fhxH2rASAUlcFhdrMSFzMFuuqLpZwWyAPGcijd201QDdaZUCg01c2oZgSg7zPSqJO0Go7TYbo0YeG5HWT5nNGiIdMxoEiTM/AGnpo8IexYrGysh6fFXZ6jJo171WZdPHlBStjC9IpeoG1lCKoAvAEYjXxfRKWHpHBYW2ig3SQt9kvSiSq33JliW2z0H/QJGel4qQQf2h6X2LS1jaIaVuitCrOihXZ5NammEhLw4koMBLCtKLIcy3T4HlUr3HJnocX3n4dMAMajVdkW+1ueTJIQ6ElM1wV2T+Ov1TQr34IdMoVuGww4ahcUV/c2IuPsWqDgNmCrjWi05gEOYUMFrTcQAACodbFxS7a3TpzUZPIJnWPAoLUcWVdn0UiGFKuyzkoeqe1OqMPyprqDl//K8="
